title: Butterfly Jekyll Theme
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A beautiful Jekyll theme inspired by Hexo Butterfly, featuring modern design,
  dark mode support, and smooth animations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Theme Settings (Butterfly specific)
butterfly:
  # Navigation
  nav:
    logo: 
      text: "Butterfly"
    menu:
      Home: /
      Archives: /archives/
      Tags: /tags/
      Categories: /categories/
      About: /about/

  # Footer
  footer:
    since: 2024
    custom_text: "Powered by Jekyll & Butterfly Theme"

  # Social Links
  social:
    github: https://github.com/
    twitter: https://twitter.com/
    instagram: https://instagram.com/
    email: mailto:your-email@example.com

  # Theme Features
  darkmode:
    enable: true
    button: true
    autoChangeMode: false

  # Code highlighting
  highlight:
    theme: github
    line_number: true
    auto_detect: false
    tab_replace: ''

  # Animations
  animate:
    enable: true
    offset: 100

  # Cover settings
  index_img: /assets/img/bg.jpg
  default_cover: /assets/img/default-cover.jpg

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
