# Site settings
title: "Butterfly Jekyll Theme"
description: "A beautiful Jekyll theme inspired by Hexo Butterfly"
url: ""
baseurl: ""
permalink: /:year/:month/:day/:title/

# Author
author:
  name: "Site Author"
  email: "author@example.com"
  avatar: "/assets/img/butterfly-icon.png"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - gulpfile.js
  - package.json

# Theme Configuration
theme_config:
  # Navigation
  nav:
    logo: 
    display_title: true
    fixed: false
  
  # Menu
  menu:
    Home: /
    Archives: /archives/
    Categories: /categories/
    Tags: /tags/
    About: /about/
  
  # Social Links
  social:
    github: ""
    email: ""
    twitter: ""
  
  # Code blocks
  code_blocks:
    theme: "light"
    copy: true
    language: true
    shrink: false
  
  # Images
  favicon: "/assets/img/favicon.png"
  avatar:
    img: "/assets/img/butterfly-icon.png"
    effect: false
  
  # Cover settings
  cover:
    index_enable: true
    aside_enable: true
    archives_enable: true
    default_cover: []
  
  # Post meta
  post_meta:
    page:
      date_type: "created"
      date_format: "date"
      categories: true
      tags: false
      label: true
    post:
      position: "left"
      date_type: "both"
      date_format: "date"
      categories: true
      tags: true
      label: true
  
  # Aside settings
  aside:
    enable: true
    hide: false
    display:
      archive: true
      tag: true
      category: true
  
  # Footer
  footer:
    owner:
      enable: true
      since: 2023
    custom_text: ""
    copyright: true
  
  # Background
  background: ""
  disable_top_img: false
  default_top_img: ""
  index_img: ""
  archive_img: ""
  tag_img: ""
  category_img: ""
  footer_img: false
  
  # 404 page
  error_404:
    enable: true
    subtitle: "Page Not Found"
    background: "/assets/img/error-page.png"
  
  # Search
  search:
    enable: true
    type: "local"
  
  # Comments
  comments:
    enable: false
    type: ""
  
  # Analytics
  analytics:
    google: ""
    baidu: ""
  
  # Other features
  related_post:
    enable: true
    limit: 6
  
  toc:
    enable: true
    number: true
    expand: false
    style_simple: false
  
  reward:
    enable: false
    QR_code: []
  
  post_pagination: true
  
  # Loading animation
  loading:
    enable: true
    gif: "/assets/img/loading.gif"
  
  # PWA
  pwa:
    enable: false
  
  # Dark mode
  display_mode: "auto"
  
  # Font
  font:
    global_font_size: ""
    code_font_size: ""
    font_family: ""
    code_font_family: ""
